const $ = s => document.querySelector(s);
const camera=$('#camera'), uploaded=$('#uploaded'), demo=$('#demo'), guides=$('#guides');
const g=guides.getContext('2d'), demoCtx=demo.getContext('2d');
let stream=null, facing='environment', source='none', guide='thirds', guideVisible=true, resultBlob=null, currentDeviceId=null;
const guideData=[
  ['thirds','Thirds','Place your subject on an intersection'],
  ['centered','Centered','Build the frame around one clear subject'],
  ['golden','Golden ratio','Follow the curve toward your subject'],
  ['symmetry','Symmetry','Align the scene across the centre'],
  ['leading','Leading lines','Let strong lines point to the subject'],
  ['vshape','V-shape','Use converging lines to hold attention'],
  ['diagonals','Diagonals','Add movement with a rising or falling line'],
  ['scurve','S-curve','Guide the eye gently through the scene'],
  ['repetition','Repetition','Fill the frame with a repeating rhythm'],
  ['juxtaposition','Juxtaposition','Set contrasting shapes side by side'],
  ['none','Clean','Capture without a guide']
];
const rail=$('#rail');
guideData.forEach(([id,name])=>{const b=document.createElement('button');b.className='guide-chip';b.type='button';b.role='option';b.dataset.guide=id;b.textContent=name;b.setAttribute('aria-selected',id===guide);b.onclick=()=>selectGuide(id);rail.appendChild(b)});
function selectGuide(id,fromCoach=false){guide=id;document.querySelectorAll('.guide-chip').forEach(x=>x.setAttribute('aria-selected',x.dataset.guide===id));const item=guideData.find(x=>x[0]===id);$('#guideName').textContent=item[1];$('#guideHint').textContent=item[2];guideVisible=id!=='none';$('#hideGuides').classList.toggle('active',guideVisible);drawGuides();document.querySelector(`[data-guide="${id}"]`).scrollIntoView({inline:'center',block:'nearest',behavior:fromCoach?'auto':'smooth'})}
window.framefinderSelectGuide=selectGuide;window.framefinderSource=()=>source;
function sizeCanvases(){const r=$('#stage').getBoundingClientRect(), d=Math.min(devicePixelRatio||1,2);guides.width=r.width*d;guides.height=r.height*d;g.setTransform(d,0,0,d,0,0);drawGuides();}
function path(ctx,w,h,id){const pad=Math.min(w,h)*.075,x0=pad,y0=pad,x1=w-pad,y1=h-pad,W=x1-x0,H=y1-y0;ctx.beginPath();
 if(id==='thirds'){[1,2].forEach(i=>{ctx.moveTo(x0+W*i/3,y0);ctx.lineTo(x0+W*i/3,y1);ctx.moveTo(x0,y0+H*i/3);ctx.lineTo(x1,y0+H*i/3)})}
 if(id==='centered'){ctx.moveTo(w/2,y0);ctx.lineTo(w/2,y1);ctx.moveTo(x0,h/2);ctx.lineTo(x1,h/2);ctx.arc(w/2,h/2,Math.min(W,H)*.18,0,Math.PI*2)}
 if(id==='symmetry'){ctx.moveTo(w/2,y0);ctx.lineTo(w/2,y1);ctx.moveTo(w/2-8,y0+15);ctx.lineTo(w/2,y0);ctx.lineTo(w/2+8,y0+15);ctx.moveTo(w/2-8,y1-15);ctx.lineTo(w/2,y1);ctx.lineTo(w/2+8,y1-15)}
 if(id==='leading'){const cx=w/2,cy=h*.48;[[x0,y0],[x1,y0],[x0,y1],[x1,y1]].forEach(([x,y])=>{ctx.moveTo(x,y);ctx.lineTo(cx,cy)});ctx.ellipse(cx,cy,W*.11,H*.18,0,0,Math.PI*2)}
 if(id==='vshape'){ctx.moveTo(x0,y0);ctx.lineTo(w/2,y1);ctx.lineTo(x1,y0);ctx.moveTo(x0+W*.18,y0);ctx.lineTo(w/2,y1);ctx.lineTo(x1-W*.18,y0)}
 if(id==='diagonals'){ctx.moveTo(x0,y1);ctx.lineTo(x1,y0);ctx.moveTo(x0,y1-H*.34);ctx.lineTo(x0+W*.65,y0)}
 if(id==='scurve'){ctx.moveTo(x1-W*.18,y0);ctx.bezierCurveTo(x0-W*.05,y0+H*.12,x1+W*.05,y0+H*.62,x0+W*.18,y1)}
 if(id==='repetition'){const rw=W*.22,rh=H*.22;for(let row=0;row<3;row++)for(let col=0;col<3;col++){const x=x0+col*(W-rw)/2,y=y0+row*(H-rh)/2;ctx.roundRect(x,y,rw,rh,Math.min(rw,rh)*.24)}}
 if(id==='juxtaposition'){ctx.rect(x0,y0,W*.42,H);ctx.rect(x0+W*.58,y0,W*.42,H);ctx.moveTo(x0+W*.42,y1);ctx.lineTo(x0+W*.58,y0)}
 if(id==='golden'){const phi=1.618;let bx=x0,by=y0,bw=W,bh=H;for(let i=0;i<7;i++){if(bw>bh){const sq=bh;ctx.rect(bx,by,sq,sq);ctx.arc(bx+sq,by+sq,sq,-Math.PI,-Math.PI/2);bx+=sq;bw-=sq}else{const sq=bw;ctx.rect(bx,by,sq,sq);ctx.arc(bx,by+sq,sq,-Math.PI/2,0);by+=sq;bh-=sq}if(bw<2||bh<2)break}}
}
function drawGuides(){const w=guides.clientWidth,h=guides.clientHeight;g.clearRect(0,0,w,h);if(!guideVisible||guide==='none'||source==='none')return;g.save();g.strokeStyle='rgba(255,255,255,.9)';g.lineWidth=1.15;g.shadowColor='rgba(0,0,0,.6)';g.shadowBlur=5;path(g,w,h,guide);g.stroke();g.restore();}
async function startCamera(deviceId){if(!navigator.mediaDevices?.getUserMedia){showBlocked();return}currentDeviceId=deviceId||currentDeviceId;stopCamera();try{const video=currentDeviceId?{deviceId:{exact:currentDeviceId},width:{ideal:1920},height:{ideal:1080}}:{facingMode:{ideal:facing},width:{ideal:1920},height:{ideal:1080}};stream=await navigator.mediaDevices.getUserMedia({video,audio:false});camera.srcObject=stream;await camera.play();source='camera';camera.hidden=false;uploaded.hidden=demo.hidden=true;showReady();window.ProControls?.attach(stream)}catch(e){console.warn('Camera unavailable',e.name);if(currentDeviceId){currentDeviceId=null;startCamera()}else showBlocked()}}
window.framefinderRestartCamera=async id=>{if(source==='camera')await startCamera(id)};
function stopCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;window.SceneCoach?.stop();window.ProControls?.detach()}
function showReady(){$('#welcome').hidden=true;$('#permissionHelp').hidden=true;$('#controls').hidden=false;$('#guideTitle').hidden=false;drawGuides();const el=source==='camera'?camera:source==='upload'?uploaded:demo;window.SceneCoach?.start(el,source)}
function showBlocked(){$('#welcome').hidden=true;$('#permissionHelp').hidden=false}
function drawDemo(){const r=$('#stage').getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);demo.width=r.width*d;demo.height=r.height*d;demoCtx.setTransform(d,0,0,d,0,0);const w=r.width,h=r.height;let grd=demoCtx.createLinearGradient(0,0,w,h);grd.addColorStop(0,'#789f93');grd.addColorStop(.46,'#d5a46c');grd.addColorStop(1,'#17272f');demoCtx.fillStyle=grd;demoCtx.fillRect(0,0,w,h);demoCtx.fillStyle='#101b20';demoCtx.fillRect(0,h*.68,w,h*.32);demoCtx.fillStyle='rgba(255,247,218,.9)';demoCtx.beginPath();demoCtx.arc(w*.68,h*.34,w*.09,0,Math.PI*2);demoCtx.fill();demoCtx.fillStyle='#1c3034';for(let i=0;i<5;i++){const x=w*(.08+i*.2);demoCtx.beginPath();demoCtx.moveTo(x,h*.68);demoCtx.lineTo(x+w*.07,h*.32);demoCtx.lineTo(x+w*.14,h*.68);demoCtx.fill()}source='demo';demo.hidden=false;camera.hidden=uploaded.hidden=true;showReady()}
function useUpload(file){if(!file)return;const url=URL.createObjectURL(file);uploaded.onload=()=>URL.revokeObjectURL(url);uploaded.src=url;source='upload';uploaded.hidden=false;camera.hidden=demo.hidden=true;showReady()}
function coverRect(sw,sh,dw,dh){const sr=sw/sh,dr=dw/dh;return sr>dr?{sx:(sw-sh*dr)/2,sy:0,sw:sh*dr,sh}:{sx:0,sy:(sh-sw/dr)/2,sw,sh:sw/dr}}
async function capture(){const r=$('#stage').getBoundingClientRect(),scale=Math.min(devicePixelRatio||1,2),out=document.createElement('canvas');out.width=Math.round(r.width*scale);out.height=Math.round(r.height*scale);const c=out.getContext('2d');let el,sw,sh;if(source==='camera'){el=camera;sw=el.videoWidth;sh=el.videoHeight}else if(source==='upload'){el=uploaded;sw=el.naturalWidth;sh=el.naturalHeight}else{el=demo;sw=el.width;sh=el.height}if(!sw||!sh)return;const q=coverRect(sw,sh,out.width,out.height);if(source==='camera'&&facing==='user'){c.save();c.translate(out.width,0);c.scale(-1,1);c.drawImage(el,q.sx,q.sy,q.sw,q.sh,0,0,out.width,out.height);c.restore()}else c.drawImage(el,q.sx,q.sy,q.sw,q.sh,0,0,out.width,out.height);if(guideVisible&&guide!=='none'){c.save();c.scale(scale,scale);c.strokeStyle='rgba(255,255,255,.92)';c.lineWidth=1.2;c.shadowColor='rgba(0,0,0,.65)';c.shadowBlur=5;path(c,r.width,r.height,guide);c.stroke();c.restore()}resultBlob=await new Promise(ok=>out.toBlob(ok,'image/jpeg',.94));$('#result').src=URL.createObjectURL(resultBlob);$('#resultDialog').showModal()}
async function saveResult(){if(!resultBlob)return;const file=new File([resultBlob],`framefinder-${Date.now()}.jpg`,{type:'image/jpeg'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'My Framefinder shot'});return}catch(e){if(e.name==='AbortError')return}}const a=document.createElement('a');a.href=URL.createObjectURL(resultBlob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
camera.addEventListener('click',e=>{if(window.ProControls?.focusAvailable?.())window.ProControls.focusAt(e.clientX,e.clientY)});$('#start').onclick=startCamera;$('#retry').onclick=startCamera;$('#tryDemo').onclick=drawDemo;$('#uploadTrigger').onclick=$('#usePhoto').onclick=()=>$('#upload').click();$('#upload').onchange=e=>useUpload(e.target.files[0]);$('#flip').onclick=async()=>{currentDeviceId=null;facing=facing==='environment'?'user':'environment';if(source==='camera')await startCamera()};$('#shutter').onclick=capture;$('#hideGuides').onclick=()=>{guideVisible=!guideVisible;$('#hideGuides').classList.toggle('active',guideVisible);drawGuides()};$('#clear').onclick=()=>{stopCamera();source='none';$('#controls').hidden=true;$('#guideTitle').hidden=true;$('#welcome').hidden=false;camera.hidden=false;uploaded.hidden=demo.hidden=true;window.SceneCoach?.stop();drawGuides()};$('#retake').onclick=$('#closeResult').onclick=()=>$('#resultDialog').close();$('#save').onclick=saveResult;$('#info').onclick=()=>$('#aboutDialog').showModal();$('#closeAbout').onclick=()=>$('#aboutDialog').close();window.addEventListener('resize',sizeCanvases);document.addEventListener('visibilitychange',()=>{if(document.hidden&&stream)stream.getVideoTracks().forEach(t=>t.enabled=false);else if(stream)stream.getVideoTracks().forEach(t=>t.enabled=true)});sizeCanvases();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
